CompanyName="บริษัท แรบบิท แคร์ โบรคเกอร์ จำกัด (สำนักงานใหญ่)"
CompanyAddress1="อาคาร คิวเฮาส์ ลุมพินี ชั้น 29 เลขที่ 1 ถนนสาทรใต้"
CompanyAddress2="แขวงทุ่งมหาเมฆ เขตสาทร กรุงเทพมหานคร 10120"
LeadNo="เลขที่ใบสั่งซื้อ"
LeadDate="วันที่ออกใบเสร็จ"
TemporaryReceipt="ใบเสร็จรับเงินชั่วคราว"
PolicyHolder="ชื่อผู้เอาประกัน"
InsurerName="ชื่อบริษัทประกัน"
Order="ลำดับ"
Subject="รายการ"
Amount="จำนวนเงิน (บาท)"
NetPremium="ค่าเบี้ยประกันภัยสุทธิ (รวมภาษีมูลค่าเพิ่ม)"
TotalDiscount="ส่วนลด"
TotalPremium="ราคารวม (รวมภาษีมูลค่าเพิ่ม)"
Note="หมายเหตุ"
NoteDetail="เอกสารนี้เป็นเพียงการออกใบเสร็จรับเงินชั่วคราวเท่านั้น"
Payment="ชำระค่าเบี้ยประกันภัยโดย"
CreditAndDebitCard="บัตรเครดิต / บัตรเดบิต"
PromptPayQR="พร้อมเพย์ คิวอาร์"
ReceivedBy="ผู้รับเงิน"
AuthorizedPerson="ผู้รับมอบอำนาจจากบริษัท"
AuthorizedPersonName="ไมเคิล มันเฟรด สไตรเบิล"
WarrantyTitle="ข้อแนะนำ / คำรับรอง"
Warranty1="ในกรณีที่มีการชำระเงินโดยวิธีการใด ๆ ที่นายหน้าประกันภัยไม่สามารถเรียกเก็บเงินได้ หรือมีการยกเลิกการชำระเงิน ใบเสร็จรับเงินชั่วคราวฉบับนี้เป็นอันยกเลิกทันที"
Warranty2="ความคุ้มครองตามกรมธรรม์จะเริ่มก็ต่อเมื่อได้รับการอนุมัติจากบริษัทประกันภัยเท่านั้น และหากกรมธรรม์ของท่านขาดผลบังคับการต่ออายุ จะมีผลเริ่มคุ้มครองต่อเมื่อได้รับการอนุมัติจากบริษัทประกันภัยเท่านั้น"
Warranty3="ใบเสร็จรับเงินชั่วคราวฉบับนี้จะมีผลสมบูรณ์เพื่อใช้เป็นหลักฐานในการรับชำระเงินค่าเบี้ยประกันภัย ก็ต่อเมื่อมีลายมือชื่อนายหน้าประกันภัย/ผู้รับเบี้ยประกันภัย และจะสิ้นผลทันทีที่บริษัทประกันภัยออกหลักฐานเป็นใบเสร็จรับเบี้ยประกันภัย/กรมธรรม์ประกันภัย หรือมีการยกเลิกใบคำขอเอาประกันภัย"
Warranty4="Rabbit Care เป็นแพลตฟอร์มเปรียบเทียบประกันและผลิตภัณฑ์ทางการเงินออนไลน์ Rabbit Care ไม่ใช่บริษัทประกัน แต่เป็นนายหน้าประกันภัยที่ได้รับใบอนุญาต ว00021/2557 และใบอนุญาตประกันชีวิตเลขที่ ช00011/2559"
DeliveryFee="ค่าจัดส่ง"
ProcessingFee="ค่าธรรมเนียม"
