CompanyName="Rabbit Care Broker Company Limited (Head Office)"
CompanyAddress1="1 Q.House Lumpini Building, 29th Floor, South Sathorn Road,"
CompanyAddress2="Tungmahamek, Sathorn, Bangkok 10120"
LeadNo="Order ID"
LeadDate="Receipt Date"
TemporaryReceipt="Temporary Receipt"
PolicyHolder="Policy Holder"
InsurerName="Insurer Name"
Order="Order"
Subject="Description"
Amount="Amount (THB)"
NetPremium="Subtotal (inclusive of taxes & duties)"
TotalDiscount="Discount"
TotalPremium="Total (inclusive of taxes & duties)"
Note="Note"
NoteDetail="This document is a temporary receipt document only."
Payment="Payment"
CreditAndDebitCard="Credit / Debit Card"
PromptPayQR="PromptPay QR"
ReceivedBy="Received By"
AuthorizedPerson="Authorized Person"
AuthorizedPersonName="Michael M. Steibl"
WarrantyTitle="Representations and Warranties"
Warranty1="In the event that the insurance broker has not received the premium payment or the payment has been cancelled, this temporary receipt shall be invalid forthwith."
Warranty2="The insurance coverage and/or policy renewal shall be activated once the insurer approves the policy."
Warranty3="This temporary receipt shall be deemed as complete payment evidence only with the endorsement of the insurance broker agent/ authorized person. This temporary receipt shall be invalid forthwith in the following cases (i) the insurer issues an insurance premium payment receipt / insurance policy or; (ii) the insurer rejects the insurance application."
Warranty4="Rabbit Care is a platform to select insurance and banking products. Rabbit Care is not an insurer but a licensed insurance brokerage with non-life insurance license no. Wor00021/2557 and life insurance license no. Chor00011/2559."
DeliveryFee="Delivery fee"
ProcessingFee="Processing fee"
